<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Enrichers.Thread" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Events\Webskt.EventBus.RabbitMQ\Webskt.EventBus.RabbitMQ.csproj" />
      <ProjectReference Include="..\..\Webskt.Common.Abstraction\Webskt.Common.Abstraction.csproj" />
      <ProjectReference Include="..\..\Webskt.Common\Webskt.Common.csproj" />
      <ProjectReference Include="..\..\Webskt.Workflow.Abstraction\Webskt.Workflow.Abstraction.csproj" />
      <ProjectReference Include="..\..\Webskt.Workflow\Webskt.Workflow.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\Config\serilog.json">
            <Link>serilog.json</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
