-- Replaces a client's secret hash. The plaintext is generated by the caller (ClientSecrets) and
-- shown once. Scoped by workspace; returns the number of clients updated: 0 or 1.
CREATE PROCEDURE dbo.Client_UpdateSecret
    @Id INT,
    @WorkspaceId INT,
    @SecretHash VARBINARY(32)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE dbo.Clients
    SET SecretHash = @SecretHash
    WHERE Id = @Id
      AND WorkspaceId = @WorkspaceId;

    SELECT @@ROWCOUNT AS UpdatedCount;
END
GO
