-- @Pin is generated by the caller (RegistrationPins) from the CSPRNG. It used to be cut from NEWID()
-- here, six hex characters, which is too few for the only credential on an anonymous endpoint.
-- A collision with an existing PIN fails on UQ_RegistrationPolicies_Pin and the caller retries.
CREATE PROCEDURE dbo.RegistrationPolicy_Create
    @WorkspaceId INT,
    @Name NVARCHAR(100),
    @MaxClients INT = NULL,
    @AutoApproval BIT = 1,
    @Pin NVARCHAR(20),
    @Id INT OUTPUT,
    @RefId UNIQUEIDENTIFIER OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    SET @RefId = NEWID();

    INSERT INTO dbo.RegistrationPolicies (
        WorkspaceId,
        RefId,
        Name,
        MaxClients,
        AutoApproval,
        Pin
    )
    VALUES (
        @WorkspaceId,
        @RefId,
        @Name,
        @MaxClients,
        @AutoApproval,
        @Pin
    );

    SET @Id = SCOPE_IDENTITY();
END
GO
