CREATE TABLE dbo.Workspaces (
    Id INT IDENTITY(1, 1) NOT NULL,
    RefId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500) NULL,
    OwnerUserId INT NOT NULL,
    CreatedAt DATETIME2(0) NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_Workspaces PRIMARY KEY CLUSTERED (Id ASC),
    CONSTRAINT UQ_Workspaces_RefId UNIQUE (RefId),
    CONSTRAINT FK_Workspaces_Users FOREIGN KEY (OwnerUserId) REFERENCES dbo.Users(Id)
);
GO
