<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);publish**</DefaultItemExcludes>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Wbskt.Core.Service.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
    <PackageReference Include="Microsoft.Extensions.Hosting"/>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices"/>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens"/>
    <PackageReference Include="Serilog.AspNetCore"/>
    <PackageReference Include="Microsoft.Data.SqlClient"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Wbskt.Common\Wbskt.Common.csproj"/>
    <ProjectReference Include="..\..\Wbskt.EventBus\Wbskt.EventBus.csproj"/>
  </ItemGroup>
</Project>
