<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="Microsoft.Data.SqlClient" />
        <PackageReference Include="Serilog.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\Config\serilog.json">
        <Link>serilog.json</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Webskt.Common.Abstraction\Webskt.Common.Abstraction.csproj" />
      <ProjectReference Include="..\Webskt.Common\Webskt.Common.csproj" />
      <ProjectReference Include="..\Events\Webskt.EventBus\Webskt.EventBus.csproj" />
      <ProjectReference Include="..\Events\Webskt.EventBus.RabbitMQ\Webskt.EventBus.RabbitMQ.csproj" />
      <ProjectReference Include="..\Events\Webskt.Events\Webskt.Events.csproj" />
    </ItemGroup>

</Project>
