CREATE TABLE dbo.Roles
(
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    RefId UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Roles_RefId DEFAULT NEWID(),
    TenantId INT NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(255) NULL,
    CONSTRAINT FK_Roles_Tenants FOREIGN KEY (TenantId) REFERENCES dbo.Tenants(Id),
    CONSTRAINT UQ_Roles_RefId UNIQUE (RefId),
    CONSTRAINT UQ_Roles_Tenant_Name UNIQUE (TenantId, Name)
)
GO
