CREATE TABLE dbo.Tenants (
    Id INT IDENTITY(1, 1) NOT NULL,
    RefId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500) NULL,
    CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_Tenants PRIMARY KEY CLUSTERED (Id ASC),
    CONSTRAINT UQ_Tenants_RefId UNIQUE (RefId),
    CONSTRAINT UQ_Tenants_Name UNIQUE (Name)
);
GO
