<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wbskt.Infrastructure\Wbskt.Infrastructure.csproj" />
    <ProjectReference Include="..\Models\Wbskt.Models\Wbskt.Models.csproj" />
    <ProjectReference Include="..\Wbskt.Primitives\Wbskt.Primitives.csproj" />
    <ProjectReference Include="..\Wbskt.Workflow.Abstraction\Wbskt.Workflow.Abstraction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
  </ItemGroup>

</Project>
